-- ============================================================
-- FERROVIA DEMO SEED DATA
-- Run AFTER database/schema-current.sql on a fresh schema.
-- Creates one complete Suborno Express example with:
--   * Dhaka <-> Chattogram UP/DOWN routes
--   * Operator + admin demo accounts
--   * 3 physical trainsets (one scheduled, one spare per terminal)
--   * Today's UP and DOWN trips
--   * Route/trip stops for operator Arrived/Departed tracking
--   * 3 classes, coaches, seats and trip seat inventory
--
-- Demo credentials:
--   operator@ferrovia.local / Operator123!
--   admin@ferrovia.local    / Admin123!
-- Passwords use the backend's built-in scrypt format.
-- ============================================================

-- -------------------- USERS --------------------
INSERT INTO USERS (FULL_NAME, EMAIL, PHONE, PASSWORD_HASH, ROLE)
VALUES (
    'Demo Operator',
    'operator@ferrovia.local',
    '01700000001',
    'scrypt$985e8d1c92c46892f79861543c64c3fa$7c28cd4a83a5c1885214897cb8b52e5af96ef1c4f2ea5d9e1fdb37516acffb3c3326eae57f7f56a47b1f07b36ce578cbfe41430d36b7e8581558edab69e2339e',
    'OPERATOR'
);

INSERT INTO USERS (FULL_NAME, EMAIL, PHONE, PASSWORD_HASH, ROLE)
VALUES (
    'Demo Admin',
    'admin@ferrovia.local',
    '01700000002',
    'scrypt$490444c8d6acc83010e68d7a15b7fd70$21f5ed937bf7db53181dfc51edb39fecbdce09d572396bc7731af0b4228baa2344bc8969290358e359a3580fb5fc3b9beb978928b3674867a2d99ff3ba9a1e17',
    'ADMIN'
);

-- -------------------- STATIONS --------------------
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Dhaka', 'Dhaka', 'DHA');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Cumilla', 'Cumilla', 'CML');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Feni', 'Feni', 'FEN');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Chattogram', 'Chattogram', 'CTG');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Rajshahi', 'Rajshahi', 'RAJ');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Khulna', 'Khulna', 'KHL');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Sylhet', 'Sylhet', 'SYL');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Rangpur', 'Rangpur', 'RNG');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Mymensingh', 'Mymensingh', 'MYM');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Brahmanbaria', 'Brahmanbaria', 'BRA');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Noakhali', 'Noakhali', 'NOA');
INSERT INTO STATIONS (STATION_NAME, CITY, STATION_CODE) VALUES ('Jashore', 'Jashore', 'JSR');

-- -------------------- TRAIN SERVICE --------------------
INSERT INTO TRAINS
    (TRAIN_NAME, TRAIN_TYPE, TRAIN_CODE, TRAIN_STATUS, SPARE_TRIGGER_DELAY_MIN)
VALUES
    ('Suborno Express', 'INTERCITY', 'SUBORNO', 'ACTIVE', 60);

-- -------------------- UP / DOWN ROUTES --------------------
INSERT INTO ROUTES
    (TRAIN_ID, ROUTE_CODE, DIRECTION, SOURCE_STATION_ID, DESTINATION_STATION_ID)
SELECT T.TRAIN_ID, 'SUB-UP', 'UP', S1.STATION_ID, S2.STATION_ID
FROM TRAINS T, STATIONS S1, STATIONS S2
WHERE T.TRAIN_CODE = 'SUBORNO'
  AND S1.STATION_CODE = 'DHA'
  AND S2.STATION_CODE = 'CTG';

INSERT INTO ROUTES
    (TRAIN_ID, ROUTE_CODE, DIRECTION, SOURCE_STATION_ID, DESTINATION_STATION_ID)
SELECT T.TRAIN_ID, 'SUB-DOWN', 'DOWN', S1.STATION_ID, S2.STATION_ID
FROM TRAINS T, STATIONS S1, STATIONS S2
WHERE T.TRAIN_CODE = 'SUBORNO'
  AND S1.STATION_CODE = 'CTG'
  AND S2.STATION_CODE = 'DHA';

-- -------------------- ROUTE STOP TEMPLATES --------------------
-- UP: Dhaka -> Cumilla -> Feni -> Chattogram
INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 1, NULL, 0, 0
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-UP' AND S.STATION_CODE='DHA';

INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 2, 135, 140, 110
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-UP' AND S.STATION_CODE='CML';

INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 3, 200, 205, 170
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-UP' AND S.STATION_CODE='FEN';

INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 4, 300, NULL, 320
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-UP' AND S.STATION_CODE='CTG';

-- DOWN: Chattogram -> Feni -> Cumilla -> Dhaka
INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 1, NULL, 0, 0
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-DOWN' AND S.STATION_CODE='CTG';

INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 2, 95, 100, 150
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-DOWN' AND S.STATION_CODE='FEN';

INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 3, 160, 165, 210
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-DOWN' AND S.STATION_CODE='CML';

INSERT INTO ROUTE_STOPS
    (ROUTE_ID, STATION_ID, STOP_SEQUENCE, ARRIVAL_OFFSET_MIN, DEPARTURE_OFFSET_MIN, DISTANCE_FROM_SOURCE_KM)
SELECT R.ROUTE_ID, S.STATION_ID, 4, 300, NULL, 320
FROM ROUTES R, STATIONS S WHERE R.ROUTE_CODE='SUB-DOWN' AND S.STATION_CODE='DHA';

-- Run every day for demo purposes.
INSERT INTO TRAIN_RUNNING_DAYS (ROUTE_ID, DAY_CODE, DEPARTURE_MINUTE)
SELECT R.ROUTE_ID, D.DAY_CODE, 420
FROM ROUTES R
CROSS JOIN (
    SELECT 'SAT' DAY_CODE FROM DUAL UNION ALL SELECT 'SUN' FROM DUAL UNION ALL
    SELECT 'MON' FROM DUAL UNION ALL SELECT 'TUE' FROM DUAL UNION ALL
    SELECT 'WED' FROM DUAL UNION ALL SELECT 'THU' FROM DUAL UNION ALL SELECT 'FRI' FROM DUAL
) D
WHERE R.ROUTE_CODE='SUB-UP';

INSERT INTO TRAIN_RUNNING_DAYS (ROUTE_ID, DAY_CODE, DEPARTURE_MINUTE)
SELECT R.ROUTE_ID, D.DAY_CODE, 840
FROM ROUTES R
CROSS JOIN (
    SELECT 'SAT' DAY_CODE FROM DUAL UNION ALL SELECT 'SUN' FROM DUAL UNION ALL
    SELECT 'MON' FROM DUAL UNION ALL SELECT 'TUE' FROM DUAL UNION ALL
    SELECT 'WED' FROM DUAL UNION ALL SELECT 'THU' FROM DUAL UNION ALL SELECT 'FRI' FROM DUAL
) D
WHERE R.ROUTE_CODE='SUB-DOWN';

-- -------------------- PHYSICAL TRAINSETS --------------------
-- SUB-01 is reserved for today's UP trip.
-- SUB-02 stays spare at Dhaka, SUB-03 stays spare at Chattogram.
INSERT INTO TRAINSETS (TRAIN_ID, TRAINSET_CODE, STATUS, CURRENT_STATION_ID)
SELECT T.TRAIN_ID, 'SUB-01', 'RESERVED', S.STATION_ID
FROM TRAINS T, STATIONS S WHERE T.TRAIN_CODE='SUBORNO' AND S.STATION_CODE='DHA';

INSERT INTO TRAINSETS (TRAIN_ID, TRAINSET_CODE, STATUS, CURRENT_STATION_ID)
SELECT T.TRAIN_ID, 'SUB-02', 'SPARE', S.STATION_ID
FROM TRAINS T, STATIONS S WHERE T.TRAIN_CODE='SUBORNO' AND S.STATION_CODE='DHA';

INSERT INTO TRAINSETS (TRAIN_ID, TRAINSET_CODE, STATUS, CURRENT_STATION_ID)
SELECT T.TRAIN_ID, 'SUB-03', 'SPARE', S.STATION_ID
FROM TRAINS T, STATIONS S WHERE T.TRAIN_CODE='SUBORNO' AND S.STATION_CODE='CTG';

-- -------------------- CLASSES / COACHES / SEATS --------------------
INSERT INTO CLASS_TYPES (CLASS_NAME, CLASS_CODE) VALUES ('SHOVAN', 'S_CHAIR');
INSERT INTO CLASS_TYPES (CLASS_NAME, CLASS_CODE) VALUES ('SNIGDHA', 'SN');
INSERT INTO CLASS_TYPES (CLASS_NAME, CLASS_CODE) VALUES ('AC SEAT', 'AC_S');

INSERT INTO COACHES (TRAIN_ID, CLASS_ID, COACH_CODE, COACH_ORDER)
SELECT T.TRAIN_ID, C.CLASS_ID, 'A', 1 FROM TRAINS T, CLASS_TYPES C
WHERE T.TRAIN_CODE='SUBORNO' AND C.CLASS_CODE='S_CHAIR';

INSERT INTO COACHES (TRAIN_ID, CLASS_ID, COACH_CODE, COACH_ORDER)
SELECT T.TRAIN_ID, C.CLASS_ID, 'B', 2 FROM TRAINS T, CLASS_TYPES C
WHERE T.TRAIN_CODE='SUBORNO' AND C.CLASS_CODE='SN';

INSERT INTO COACHES (TRAIN_ID, CLASS_ID, COACH_CODE, COACH_ORDER)
SELECT T.TRAIN_ID, C.CLASS_ID, 'C', 3 FROM TRAINS T, CLASS_TYPES C
WHERE T.TRAIN_CODE='SUBORNO' AND C.CLASS_CODE='AC_S';

-- 12 seats per demo coach.
INSERT INTO SEATS (COACH_ID, SEAT_NUMBER, SEAT_TYPE)
SELECT C.COACH_ID, TO_CHAR(LVL),
       CASE WHEN MOD(LVL,4) IN (1,0) THEN 'WINDOW' ELSE 'AISLE' END
FROM COACHES C
CROSS JOIN (SELECT LEVEL LVL FROM DUAL CONNECT BY LEVEL <= 12)
WHERE C.TRAIN_ID = (SELECT TRAIN_ID FROM TRAINS WHERE TRAIN_CODE='SUBORNO');

INSERT INTO FARE_RULES (TRAIN_ID, CLASS_ID, RATE_PER_KM, BASE_FARE)
SELECT T.TRAIN_ID, C.CLASS_ID,
       CASE C.CLASS_CODE WHEN 'S_CHAIR' THEN 1.50 WHEN 'SN' THEN 2.50 ELSE 3.50 END,
       CASE C.CLASS_CODE WHEN 'S_CHAIR' THEN 50 WHEN 'SN' THEN 100 ELSE 150 END
FROM TRAINS T
CROSS JOIN CLASS_TYPES C
WHERE T.TRAIN_CODE='SUBORNO'
  AND C.CLASS_CODE IN ('S_CHAIR','SN','AC_S');

-- -------------------- TODAY'S DEMO TRIPS --------------------
-- UP starts five minutes after this seed is run.
INSERT INTO TRIPS
    (TRAIN_ID, ROUTE_ID, JOURNEY_DATE, SCHEDULED_DEPARTURE, SCHEDULED_ARRIVAL,
     TRIP_STATUS, OPERATOR_USER_ID)
SELECT T.TRAIN_ID,
       R.ROUTE_ID,
       TRUNC(SYSDATE),
       SYSTIMESTAMP + NUMTODSINTERVAL(5, 'MINUTE'),
       SYSTIMESTAMP + NUMTODSINTERVAL(305, 'MINUTE'),
       'SCHEDULED',
       U.USER_ID
FROM TRAINS T, ROUTES R, USERS U
WHERE T.TRAIN_CODE='SUBORNO'
  AND R.TRAIN_ID=T.TRAIN_ID
  AND R.ROUTE_CODE='SUB-UP'
  AND U.EMAIL='operator@ferrovia.local';

-- DOWN starts seven hours after this seed is run.
INSERT INTO TRIPS
    (TRAIN_ID, ROUTE_ID, JOURNEY_DATE, SCHEDULED_DEPARTURE, SCHEDULED_ARRIVAL,
     TRIP_STATUS, OPERATOR_USER_ID)
SELECT T.TRAIN_ID,
       R.ROUTE_ID,
       TRUNC(SYSDATE),
       SYSTIMESTAMP + NUMTODSINTERVAL(420, 'MINUTE'),
       SYSTIMESTAMP + NUMTODSINTERVAL(720, 'MINUTE'),
       'SCHEDULED',
       U.USER_ID
FROM TRAINS T, ROUTES R, USERS U
WHERE T.TRAIN_CODE='SUBORNO'
  AND R.TRAIN_ID=T.TRAIN_ID
  AND R.ROUTE_CODE='SUB-DOWN'
  AND U.EMAIL='operator@ferrovia.local';

-- Materialize route-stop timetable into each actual trip.
INSERT INTO TRIP_STOPS
    (TRIP_ID, ROUTE_STOP_ID, STATION_ID, STOP_SEQUENCE,
     SCHEDULED_ARRIVAL, SCHEDULED_DEPARTURE)
SELECT T.TRIP_ID,
       RS.ROUTE_STOP_ID,
       RS.STATION_ID,
       RS.STOP_SEQUENCE,
       CASE WHEN RS.ARRIVAL_OFFSET_MIN IS NULL THEN NULL
            ELSE T.SCHEDULED_DEPARTURE + NUMTODSINTERVAL(RS.ARRIVAL_OFFSET_MIN, 'MINUTE') END,
       CASE WHEN RS.DEPARTURE_OFFSET_MIN IS NULL THEN NULL
            ELSE T.SCHEDULED_DEPARTURE + NUMTODSINTERVAL(RS.DEPARTURE_OFFSET_MIN, 'MINUTE') END
FROM TRIPS T
JOIN ROUTE_STOPS RS ON RS.ROUTE_ID = T.ROUTE_ID
WHERE T.TRAIN_ID = (SELECT TRAIN_ID FROM TRAINS WHERE TRAIN_CODE='SUBORNO');

-- Initial physical assignment only for the UP trip.
-- If UP is <60 minutes late, SUB-01 will be reserved for DOWN on completion.
-- If UP reaches >=60 minutes delay at a departed station, SUB-03 will be reserved instead.
INSERT INTO TRAINSET_ASSIGNMENTS
    (TRIP_ID, TRAINSET_ID, TRAIN_ID, ASSIGNMENT_TYPE, ASSIGNMENT_STATUS, REASON)
SELECT T.TRIP_ID, TS.TRAINSET_ID, T.TRAIN_ID, 'NORMAL', 'RESERVED', 'Initial demo assignment'
FROM TRIPS T
JOIN ROUTES R ON R.ROUTE_ID=T.ROUTE_ID
JOIN TRAINSETS TS ON TS.TRAIN_ID=T.TRAIN_ID AND TS.TRAINSET_CODE='SUB-01'
WHERE R.ROUTE_CODE='SUB-UP';

-- Generate trip-seat inventory for both trips.
INSERT INTO TRIP_SEATS (TRIP_ID, SEAT_ID, SEAT_STATUS)
SELECT T.TRIP_ID, S.SEAT_ID, 'AVAILABLE'
FROM TRIPS T
JOIN COACHES C ON C.TRAIN_ID=T.TRAIN_ID
JOIN SEATS S ON S.COACH_ID=C.COACH_ID
WHERE T.TRAIN_ID=(SELECT TRAIN_ID FROM TRAINS WHERE TRAIN_CODE='SUBORNO');

COMMIT;

-- Useful checks after seeding:
-- SELECT * FROM VW_TRAINSET_STATUS ORDER BY TRAINSET_CODE;
-- SELECT * FROM VW_LIVE_TRAIN_STATUS ORDER BY SCHEDULED_DEPARTURE;
-- SELECT TRIP_ID, STATION_ID, STOP_SEQUENCE, SCHEDULED_ARRIVAL, SCHEDULED_DEPARTURE,
--        ACTUAL_ARRIVAL, ACTUAL_DEPARTURE, STOP_STATUS
-- FROM TRIP_STOPS ORDER BY TRIP_ID, STOP_SEQUENCE;
